export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#0f0f0f] text-white">
      {/* Hero Section */}
      <section className="px-6 pt-28 pb-16 text-center max-w-5xl mx-auto">
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight bg-gradient-to-r from-white to-gray-400 bg-clip-text text-transparent">
          Terms of Service
        </h1>
        <p className="mt-6 text-gray-400 text-lg max-w-2xl mx-auto">
          Please read these terms carefully before using Explain My Decision.
          By accessing our platform, you agree to the following conditions.
        </p>
        <p className="mt-4 text-sm text-gray-500">
          Last Updated: {new Date().getFullYear()}
        </p>
      </section>

      {/* Content Section */}
      <section className="px-6 pb-24">
        <div className="max-w-4xl mx-auto space-y-14 text-gray-300 leading-relaxed">

          <div>
            <h2 className="text-2xl font-semibold text-white mb-4">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using Explain My Decision (“EMD”), you agree to
              be legally bound by these Terms of Service. If you do not agree
              with any part of these terms, you must discontinue use of the
              platform immediately.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white mb-4">
              2. Description of Service
            </h2>
            <p>
              EMD is an AI-powered explanation engine that analyzes user-provided
              questions and answers to generate structured, step-by-step reasoning
              using artificial intelligence technologies including Google Gemini.
            </p>
            <p className="mt-4">
              The service is intended for educational and informational purposes
              only and does not provide professional certification, legal,
              medical, or financial advice.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white mb-4">
              3. AI Content Disclaimer
            </h2>
            <p>
              Content generated by EMD is produced by AI systems and may contain
              inaccuracies or incomplete reasoning. While we aim for clarity and
              logical correctness, we do not guarantee 100% accuracy.
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2">
              <li>You are responsible for verifying critical information.</li>
              <li>EMD does not replace expert consultation.</li>
              <li>AI-generated explanations may evolve over time.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white mb-4">
              4. User Conduct
            </h2>
            <p>
              You agree not to misuse the platform. Prohibited activities include:
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2">
              <li>Submitting unlawful or harmful content</li>
              <li>Attempting to exploit or reverse engineer the system</li>
              <li>Using the platform for deceptive or fraudulent purposes</li>
              <li>Violating applicable laws or regulations</li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white mb-4">
              5. Accounts & Authentication
            </h2>
            <p>
              EMD uses Supabase for authentication. You are responsible for
              maintaining the confidentiality of your login credentials and
              for activities occurring under your account.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white mb-4">
              6. Intellectual Property
            </h2>
            <p>
              All branding, design, and proprietary features of EMD are owned
              by Explain My Decision.
            </p>
            <p className="mt-4">
              Users retain ownership of the content they submit. By submitting
              content, you grant EMD permission to process it solely for the
              purpose of generating explanations.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white mb-4">
              7. Limitation of Liability
            </h2>
            <p>
              To the fullest extent permitted by law, EMD shall not be liable
              for any indirect, incidental, consequential, or special damages
              arising from your use of the platform.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white mb-4">
              8. Service Changes
            </h2>
            <p>
              We reserve the right to modify, suspend, or discontinue the
              platform at any time without prior notice.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white mb-4">
              9. Termination
            </h2>
            <p>
              We may suspend or terminate access if a user violates these Terms.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white mb-4">
              10. Governing Law
            </h2>
            <p>
              These Terms shall be governed in accordance with applicable
              jurisdictional laws.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white mb-4">
              11. Contact
            </h2>
            <p>
              For any questions regarding these Terms:
            </p>
            <p className="mt-3 text-gray-400">
              support@explainmydecision.com
            </p>
          </div>

        </div>
      </section>
    </div>
  );
}
