// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdxepwdtdeqwoucqlaru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkeGVwd2R0ZGVxd291Y3FsYXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3MDU2NjcsImV4cCI6MjA4NTI4MTY2N30.YCHlKRPvummTA0PL4Do8NqKbg_LrGTtUZtistnMMMlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});